on:
  issue_comment:
    types: [created, edited]
name: /bloat command

jobs:
  check_comment:
    runs-on: macos-10.14
    name: bloat comment
    if: startsWith(github.event.comment.body, '/bloat')
    steps:
      - run: brew install cairo
      - run: mkdir '.bloatcmp'
      - uses: actions/checkout@v1
        with:
            ref: master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build --release --examples
      - run: |
           ls -l target/release/examples | awk '{print $9 "\t" $5}' | grep --invert-match "[\.-]" > ".bloatcmp/old.txt"
        shell: bash
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build --release --examples
      - name: Dump file sizes
        run: |
           ls -l target/release/examples | awk '{print $9 "\t" $5}' | grep --invert-match "[\.-]" > ".bloatcmp/new.txt"
        shell: bash
      - name: compare
        uses: cmyr/bloat-cmp/compare@mater
        id: bloatcmp
      - name: comment
        uses: cmyr/bloat-cmp/reply-to-pr-comment@master
        with:
          bloat_stats: ${{ steps.bloatcmp.outputs.bloat_stats }}
          myToken: ${{ secrets.GITHUB_TOKEN }}
