on:
  push:
  pull_request:
  issue_comment:
    types: [created, edited]
name: bloat check

jobs:
  check_comment:
    runs-on: macos-10.14
    name: bloat comment
    if: (!startsWith(github.eventName, 'issue_comment') || startsWith(github.event.comment.body, '/bloat'))
    steps:
      - run: brew install cairo
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/checkout@v1
        with:
            ref: master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --examples
      - name: get old sizes
        id: old
        uses: cmyr/bloat-cmp/get-sizes@master
        with:
          paths: >
            target/release/examples/calc
            target/release/examples/scroll_colors
            target/release/examples/multiwin
            target/release/examples/textbox
            target/release/examples/custom_widget
      - run: rm -rf target/release/examples
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --examples
      - name: get new sizes
        id: new
        uses: cmyr/bloat-cmp/get-sizes@master
        with:
          paths: >
            target/release/examples/calc
            target/release/examples/scroll_colors
            target/release/examples/multiwin
            target/release/examples/textbox
            target/release/examples/custom_widget
      - name: compare
        id: bloatcmp
        uses: cmyr/bloat-cmp/compare@master
        with:
            old: ${{ steps.old.outputs.rawSizes }}
            new: ${{ steps.new.outputs.rawSizes }}
      - name: comment
        uses: cmyr/bloat-cmp/post-comment@master
        with:
          stats: ${{ steps.bloatcmp.outputs.stats }}
          myToken: ${{ secrets.GITHUB_TOKEN }}
